package com.kai.gwtwohot;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APIKEY".
 */
public class APIKey {

    private Long id;
    /** Not-null value. */
    private String permissions;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String apiId;
    /** Not-null value. */
    private String key;
    private boolean isSelected;

    public APIKey() {
    }

    public APIKey(Long id) {
        this.id = id;
    }

    public APIKey(Long id, String permissions, String name, String apiId, String key, boolean isSelected) {
        this.id = id;
        this.permissions = permissions;
        this.name = name;
        this.apiId = apiId;
        this.key = key;
        this.isSelected = isSelected;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPermissions() {
        return permissions;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPermissions(String permissions) {
        this.permissions = permissions;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getApiId() {
        return apiId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setApiId(String apiId) {
        this.apiId = apiId;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

    public boolean getIsSelected() {
        return isSelected;
    }

    public void setIsSelected(boolean isSelected) {
        this.isSelected = isSelected;
    }

}
