package com.kai.gwtwohot;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.kai.gwtwohot.APIKey;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "APIKEY".
*/
public class APIKeyDao extends AbstractDao<APIKey, Long> {

    public static final String TABLENAME = "APIKEY";

    /**
     * Properties of entity APIKey.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Permissions = new Property(1, String.class, "permissions", false, "PERMISSIONS");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property ApiId = new Property(3, String.class, "apiId", false, "API_ID");
        public final static Property Key = new Property(4, String.class, "key", false, "KEY");
        public final static Property IsSelected = new Property(5, boolean.class, "isSelected", false, "IS_SELECTED");
    };


    public APIKeyDao(DaoConfig config) {
        super(config);
    }
    
    public APIKeyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"APIKEY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PERMISSIONS\" TEXT NOT NULL ," + // 1: permissions
                "\"NAME\" TEXT NOT NULL ," + // 2: name
                "\"API_ID\" TEXT NOT NULL ," + // 3: apiId
                "\"KEY\" TEXT NOT NULL ," + // 4: key
                "\"IS_SELECTED\" INTEGER NOT NULL );"); // 5: isSelected
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"APIKEY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, APIKey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getPermissions());
        stmt.bindString(3, entity.getName());
        stmt.bindString(4, entity.getApiId());
        stmt.bindString(5, entity.getKey());
        stmt.bindLong(6, entity.getIsSelected() ? 1L: 0L);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public APIKey readEntity(Cursor cursor, int offset) {
        APIKey entity = new APIKey( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // permissions
            cursor.getString(offset + 2), // name
            cursor.getString(offset + 3), // apiId
            cursor.getString(offset + 4), // key
            cursor.getShort(offset + 5) != 0 // isSelected
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, APIKey entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPermissions(cursor.getString(offset + 1));
        entity.setName(cursor.getString(offset + 2));
        entity.setApiId(cursor.getString(offset + 3));
        entity.setKey(cursor.getString(offset + 4));
        entity.setIsSelected(cursor.getShort(offset + 5) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(APIKey entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(APIKey entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
