package com.kai.gwtwohot;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DUNGEON".
 */
public class Dungeon {

    private Long id;
    /** Not-null value. */
    private String dungeon;
    /** Not-null value. */
    private String path;
    /** Not-null value. */
    private String goldreward;
    /** Not-null value. */
    private String tokenreward;
    private boolean isSelected;
    /** Not-null value. */
    private java.util.Date dateAdded;

    public Dungeon() {
    }

    public Dungeon(Long id) {
        this.id = id;
    }

    public Dungeon(Long id, String dungeon, String path, String goldreward, String tokenreward, boolean isSelected, java.util.Date dateAdded) {
        this.id = id;
        this.dungeon = dungeon;
        this.path = path;
        this.goldreward = goldreward;
        this.tokenreward = tokenreward;
        this.isSelected = isSelected;
        this.dateAdded = dateAdded;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDungeon() {
        return dungeon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDungeon(String dungeon) {
        this.dungeon = dungeon;
    }

    /** Not-null value. */
    public String getPath() {
        return path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPath(String path) {
        this.path = path;
    }

    /** Not-null value. */
    public String getGoldreward() {
        return goldreward;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGoldreward(String goldreward) {
        this.goldreward = goldreward;
    }

    /** Not-null value. */
    public String getTokenreward() {
        return tokenreward;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTokenreward(String tokenreward) {
        this.tokenreward = tokenreward;
    }

    public boolean getIsSelected() {
        return isSelected;
    }

    public void setIsSelected(boolean isSelected) {
        this.isSelected = isSelected;
    }

    /** Not-null value. */
    public java.util.Date getDateAdded() {
        return dateAdded;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDateAdded(java.util.Date dateAdded) {
        this.dateAdded = dateAdded;
    }

}
