package com.kai.gwtwohot;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DUNGEON".
 */
public class Dungeon {

    private Long id;
    /** Not-null value. */
    private String idSelected;
    /** Not-null value. */
    private java.util.Date dateAdded;

    public Dungeon() {
    }

    public Dungeon(Long id) {
        this.id = id;
    }

    public Dungeon(Long id, String idSelected, java.util.Date dateAdded) {
        this.id = id;
        this.idSelected = idSelected;
        this.dateAdded = dateAdded;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIdSelected() {
        return idSelected;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdSelected(String idSelected) {
        this.idSelected = idSelected;
    }

    /** Not-null value. */
    public java.util.Date getDateAdded() {
        return dateAdded;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDateAdded(java.util.Date dateAdded) {
        this.dateAdded = dateAdded;
    }

}
