package com.kai.gwtwohot;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EVENT".
 */
public class Event {

    private Long id;
    /** Not-null value. */
    private String area;
    /** Not-null value. */
    private String boss;
    private int spawntime_utc_minutes;
    /** Not-null value. */
    private String zone;

    public Event() {
    }

    public Event(Long id) {
        this.id = id;
    }

    public Event(Long id, String area, String boss, int spawntime_utc_minutes, String zone) {
        this.id = id;
        this.area = area;
        this.boss = boss;
        this.spawntime_utc_minutes = spawntime_utc_minutes;
        this.zone = zone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getArea() {
        return area;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setArea(String area) {
        this.area = area;
    }

    /** Not-null value. */
    public String getBoss() {
        return boss;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBoss(String boss) {
        this.boss = boss;
    }

    public int getSpawntime_utc_minutes() {
        return spawntime_utc_minutes;
    }

    public void setSpawntime_utc_minutes(int spawntime_utc_minutes) {
        this.spawntime_utc_minutes = spawntime_utc_minutes;
    }

    /** Not-null value. */
    public String getZone() {
        return zone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setZone(String zone) {
        this.zone = zone;
    }

}
