package com.kai.gwtwohot;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FAVORITE_ITEM".
 */
public class FavoriteItem {

    private Long id;
    private int gw_item_id;

    public FavoriteItem() {
    }

    public FavoriteItem(Long id) {
        this.id = id;
    }

    public FavoriteItem(Long id, int gw_item_id) {
        this.id = id;
        this.gw_item_id = gw_item_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getGw_item_id() {
        return gw_item_id;
    }

    public void setGw_item_id(int gw_item_id) {
        this.gw_item_id = gw_item_id;
    }

}
