package com.kai.gwtwohot;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NOTIFICATION_ITEM".
 */
public class NotificationItem {

    private Long id;
    private int gw_item_id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String icon;
    private Integer buyPrice;
    private Integer sellPrice;
    private Boolean isGreater;
    private Boolean isBuy;
    private boolean isNotified;

    public NotificationItem() {
    }

    public NotificationItem(Long id) {
        this.id = id;
    }

    public NotificationItem(Long id, int gw_item_id, String name, String icon, Integer buyPrice, Integer sellPrice, Boolean isGreater, Boolean isBuy, boolean isNotified) {
        this.id = id;
        this.gw_item_id = gw_item_id;
        this.name = name;
        this.icon = icon;
        this.buyPrice = buyPrice;
        this.sellPrice = sellPrice;
        this.isGreater = isGreater;
        this.isBuy = isBuy;
        this.isNotified = isNotified;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getGw_item_id() {
        return gw_item_id;
    }

    public void setGw_item_id(int gw_item_id) {
        this.gw_item_id = gw_item_id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getIcon() {
        return icon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    public Integer getBuyPrice() {
        return buyPrice;
    }

    public void setBuyPrice(Integer buyPrice) {
        this.buyPrice = buyPrice;
    }

    public Integer getSellPrice() {
        return sellPrice;
    }

    public void setSellPrice(Integer sellPrice) {
        this.sellPrice = sellPrice;
    }

    public Boolean getIsGreater() {
        return isGreater;
    }

    public void setIsGreater(Boolean isGreater) {
        this.isGreater = isGreater;
    }

    public Boolean getIsBuy() {
        return isBuy;
    }

    public void setIsBuy(Boolean isBuy) {
        this.isBuy = isBuy;
    }

    public boolean getIsNotified() {
        return isNotified;
    }

    public void setIsNotified(boolean isNotified) {
        this.isNotified = isNotified;
    }

}
